import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { colors } from "@mui/material";
import Footer from "../../components/Footer";
import Header from "../../components/Header";
import { ThemeProvider, createTheme } from '@mui/material/styles';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white h-screen`}
      >
        <Header/>
        <nav className="flex gap-4 p-4 text-black">
          <Link href="/" className="bg-blue-200 p-2">[/]</Link>
          <Link href="home_page" className="bg-blue-200 p-2">Home</Link>
          <Link href="connexion" className="bg-blue-200 p-2">Connexion</Link>
          <Link href="home_page" className="bg-blue-200 p-2">Home</Link>
        </nav>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
